[build]
  command = "npm run build"
  publish = "build"

[[redirects]]
  from = "/api/*"
  to = "https://unemployment-claims-backend.onrender.com/api/:splat"
  status = 200

[build.environment]
  REACT_APP_API_URL = "https://unemployment-claims-backend.onrender.com/api" 