services:
  - type: web
    name: unemployment-claims
    env: python
    runtime: python3.11
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: TOGETHER_API_KEY
        sync: false
      - key: DATABASE_URL
        sync: false
    healthCheckPath: /health
    autoDeploy: true 