services:
  - type: web
    name: unemployment-claims
    env: python
    runtime: python3.11
    buildCommand: |
      pip install -r requirements.txt
      export PYTHONPATH=$PYTHONPATH:$(pwd)
    startCommand: |
      export PYTHONPATH=$PYTHONPATH:$(pwd)
      export STREAMLIT_SERVER_HEADLESS=true
      export STREAMLIT_SERVER_ENABLE_WEBSOCKET_COMPRESSION=false
      uvicorn main:app --host 0.0.0.0 --port $PORT --ws-ping-interval 20 --ws-ping-timeout 20
    envVars:
      - key: TOGETHER_API_KEY
        sync: false
      - key: DATABASE_URL
        sync: false
      - key: PYTHONPATH
        value: ${PYTHONPATH}:${PWD}
      - key: STREAMLIT_SERVER_HEADLESS
        value: "true"
      - key: STREAMLIT_SERVER_ENABLE_WEBSOCKET_COMPRESSION
        value: "false"
    healthCheckPath: /health
    autoDeploy: true 