services:
  - type: web
    name: unemployment-claims
    env: python
    runtime: python3.11
    buildCommand: |
      pip install -r requirements.txt
      export PYTHONPATH=$PYTHONPATH:$(pwd)
    startCommand: |
      export PYTHONPATH=$PYTHONPATH:$(pwd)
      uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: TOGETHER_API_KEY
        sync: false
      - key: DATABASE_URL
        sync: false
      - key: PYTHONPATH
        value: ${PYTHONPATH}:${PWD}
    healthCheckPath: /health
    autoDeploy: true 