services:
  - type: web
    name: unemployment-claims
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run frontend/app.py --server.port=$PORT --server.address=0.0.0.0
    envVars:
      - key: TOGETHER_API_KEY
        sync: false
      - key: DATABASE_URL
        sync: false
    healthCheckPath: /
    autoDeploy: true 